In [1]:
import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm

In [2]:
df = pd.read_csv(r"../data/player_stats_by_game.csv")

In [13]:
df['GAMES STARTED'].unique()

array(['Inactive', '0', 'Did Not Play', '1', 'Did Not Dress',
       'Not With Team', 'Player Suspended'], dtype=object)

In [15]:
list_ = []
for c in df.columns:
    val = c.replace(" ","_")
    list_.append(val)
    
df.columns = list_

In [16]:
df.columns = [c.replace(" ", "_") for c in df.columns]

In [17]:
# filtering on the data with multiple values for same column
active_players = df[df['GAMES_STARTED'].isin(['0','1'])]

# filtering on the data with single value for one column
# one way
inactive_players = df[df['GAMES_STARTED']=='Inactive']

# second way
did_not_play = df.query("GAMES_STARTED=='Did Not Play'")

In [20]:
did_not_play

,PLAYER_NAME,SEASON_ID,SEASON,SEASON_GAME,DATE,"PLAYER_AGE,_FEB",TEAM,HOME_TEAM,AWAY_TEAM,GAMES_STARTED,MINUTES_PLAYED,FIELD_GOALS,FIELD_GOAL_ATTEMPTS,FIELD_GOAL_PERCENTAGE,3-POINT_FIELD_GOALS,3-POINT_FIELD_GOAL_ATTEMPTS,3-POINT_FIELD_GOAL_PERCENTAGE,FREE_THROWS,FREE_THROW_ATTEMPTS,FREE_THROW_PERCENTAGE,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,TOTAL_REBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS,GAME_SCORE,PLUS/MINUS
10,Aaron Brooks,58,2007-08,7,2007-11-11,22-301,HOU,CHA,HOU,Did Not Play,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,Aaron Brooks,58,2007-08,62,2008-03-08,23-054,HOU,HOU,NOH,Did Not Play,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,Aaron Brooks,58,2007-08,64,2008-03-12,23-058,HOU,ATL,HOU,Did Not Play,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,Aaron Brooks,58,2007-08,65,2008-03-14,23-060,HOU,HOU,CHA,Did Not Play,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,Aaron Brooks,58,2007-08,66,2008-03-16,23-062,HOU,HOU,LAL,Did Not Play,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
553741,Zydrunas Ilgauskas,61,2010-11,60,2011-02-27,35-267,MIA,MIA,NYK,Did Not Play,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
553804,Zylan Cheatham,70,2019-20,42,2020-01-16,24-060,NOP,NOP,UTA,Did Not Play,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
553806,Zylan Cheatham,70,2019-20,40,2020-01-11,24-055,NOP,BOS,NOP,Did Not Play,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
553814,Zylan Cheatham,70,2019-20,14,2019-11-19,24-002,NOP,NOP,POR,Did Not Play,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
553823,Zylan Cheatham,70,2019-20,3,2019-10-26,23-343,NOP,HOU,NOP,Did Not Play,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
pd.set_option('display.max_columns',100)

In [50]:
active_players

,PLAYER_NAME,SEASON_ID,SEASON,SEASON_GAME,DATE,"PLAYER_AGE,_FEB",TEAM,HOME_TEAM,AWAY_TEAM,GAMES_STARTED,MINUTES_PLAYED,FIELD_GOALS,FIELD_GOAL_ATTEMPTS,FIELD_GOAL_PERCENTAGE,3-POINT_FIELD_GOALS,3-POINT_FIELD_GOAL_ATTEMPTS,3-POINT_FIELD_GOAL_PERCENTAGE,FREE_THROWS,FREE_THROW_ATTEMPTS,FREE_THROW_PERCENTAGE,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,TOTAL_REBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS,GAME_SCORE,PLUS/MINUS,ASSISTS_AND_POINTS,minutes_played_in_seconds,EFFICIENCY
23,Aaron Brooks,58,2007-08,26,2007-12-20,22-340,HOU,DEN,HOU,0,13:45,4.0,9.0,0.444,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0,8.0,0.7,-5.0,8.0,825,0.009697
24,Aaron Brooks,58,2007-08,27,2007-12-22,22-342,HOU,CHI,HOU,0,17:20,2.0,5.0,0.400,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,6.0,0.0,0.0,1.0,1.0,4.0,4.7,9.0,10.0,1040,0.009615
25,Aaron Brooks,58,2007-08,28,2007-12-23,22-343,HOU,DET,HOU,0,17:43,3.0,6.0,0.500,2.0,4.0,0.5,4.0,4.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,3.0,1.0,12.0,7.7,3.0,13.0,1063,0.012230
26,Aaron Brooks,58,2007-08,29,2007-12-28,22-348,HOU,MEM,HOU,0,21:14,4.0,8.0,0.500,2.0,5.0,0.4,0.0,0.0,0.0,0.0,3.0,3.0,7.0,0.0,0.0,1.0,1.0,10.0,10.4,5.0,17.0,1274,0.013344
27,Aaron Brooks,58,2007-08,30,2007-12-29,22-349,HOU,HOU,TOR,0,14:48,2.0,7.0,0.286,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4.0,0.6,3.0,5.0,888,0.005631
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
553778,Zydrunas Ilgauskas,61,2010-11,15,2010-11-24,35-172,MIA,ORL,MIA,1,24:44,3.0,7.0,0.429,0.0,0.0,0.0,1.0,2.0,0.5,3.0,3.0,6.0,1.0,1.0,0.0,0.0,5.0,7.0,5.6,5.0,8.0,1484,0.005391
553779,Zydrunas Ilgauskas,61,2010-11,16,2010-11-26,35-174,MIA,MIA,PHI,1,16:17,2.0,3.0,0.667,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0,5.0,0.0,0.0,0.0,0.0,2.0,4.0,3.8,4.0,4.0,977,0.004094
553780,Zydrunas Ilgauskas,61,2010-11,17,2010-11-27,35-175,MIA,DAL,MIA,1,10:57,0.0,3.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,3.0,0.0,2.0,0.0,0.0,3.0,0.0,0.4,-15.0,0.0,657,0.000000
553789,Zylan Cheatham,70,2019-20,12,2019-11-16,23-364,NOP,MIA,NOP,0,13:52,1.0,3.0,0.333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,1.0,0.0,0.0,1.0,3.0,2.0,-0.3,-17.0,3.0,832,0.003606
553805,Zylan Cheatham,70,2019-20,41,2020-01-13,24-057,NOP,DET,NOP,0,10:56,1.0,1.0,1.000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,3.0,1.0,0.0,1.0,2.0,2.0,2.0,1.6,-7.0,3.0,656,0.004573

In [21]:
active_players['ASSISTS_AND_POINTS'] = active_players['ASSISTS'] + active_players['POINTS']

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [51]:
def calculate_time_in_seconds(minutes_played):
    minutes, seconds = minutes_played.split(":")
    total = 60*int(minutes) + int(seconds)
    return total

active_players['minutes_played_in_seconds'] = active_players.apply(
    lambda x: calculate_time_in_seconds(x['MINUTES_PLAYED']), axis=1)

active_players['ASSISTS_AND_POINTS']  = active_players['ASSISTS'] + active_players['POINTS'] + active_players['TOTAL_REBOUNDS']
active_players['EFFICIENCY'] = active_players['ASSISTS_AND_POINTS'] / active_players['minutes_played_in_seconds']

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [52]:
active_players =active_players[active_players['minutes_played_in_seconds']>600]

In [54]:
active_players.groupby('PLAYER_NAME')[['EFFICIENCY']].max().sort_values('EFFICIENCY', ascending=False)

                       EFFICIENCY
PLAYER_NAME
Giannis Antetokounmpo    0.038880
Boban Marjanović         0.038772
James Harden             0.038566
Thomas Robinson          0.037643
Luka Dončić              0.036601
...                           ...
Joe Chealey              0.002674
Matt Mooney              0.002581
Vince Edwards            0.001389
Jarred Vanderbilt        0.001351
Melvin Frazier           0.000000

[1269 rows x 1 columns]

In [32]:
31*60

1860

In [ ]:
active_players[['']]

In [ ]:
df = df[df['GAMES STARTED'].isin(['0','1'])]

In [8]:
player_names = df['PLAYER NAME'].unique()